# Generated by Django 2.2.12 on 2020-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0005_auto_20200622_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='intro',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
