# Generated by Django 2.2.12 on 2020-06-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0007_work_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intro',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-created_at']},
        ),
    ]
