# Generated by Django 2.2.12 on 2020-07-03 04:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0009_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
