# Generated by Django 2.2.12 on 2020-09-02 08:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0010_blog_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ['-start_date']},
        ),
    ]
