# Generated by Django 2.2.12 on 2020-09-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0011_auto_20200902_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
