# Generated by Django 2.2.12 on 2020-09-03 07:14

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0012_auto_20200902_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
