# Generated by Django 2.2.12 on 2020-09-03 12:48

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0013_auto_20200903_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(),
        ),
    ]
