# Generated by Django 2.2.12 on 2020-09-03 13:49

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):
    dependencies = [
        ('personal', '0014_auto_20200903_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
